/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rollcall;

import javax.swing.JOptionPane;
import java.util.Date;

public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsignout = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        btndate = new javax.swing.JButton();
        btndaymissed = new javax.swing.JButton();
        btndaysigned = new javax.swing.JButton();
        btnportal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setText("logo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-5, 0, 600, 83);

        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 120, 28, 14);

        jLabel3.setText("MATRIC NUMBER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 120, 100, 14);

        jLabel4.setText("ROOM NUMBER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 120, 90, 14);

        jLabel5.setText("HALL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 120, 24, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ENTER CODE HERE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 190, 220, 30);
        getContentPane().add(tfcode);
        tfcode.setBounds(180, 240, 230, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("TOTAL DAY MISSED:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 290, 150, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setText("TOTAL DAY SIGNED:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 340, 140, 17);

        btnsignout.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnsignout.setText("DONE");
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout);
        btnsignout.setBounds(0, 380, 90, 21);

        btnsubmit.setFont(new java.awt.Font("Times New Roman", 2, 10)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.setToolTipText("");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit);
        btnsubmit.setBounds(460, 240, 67, 21);

        btndate.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btndate.setText("DATE");
        btndate.setToolTipText("");
        btndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndateActionPerformed(evt);
            }
        });
        getContentPane().add(btndate);
        btndate.setBounds(450, 190, 80, 25);

        btndaymissed.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btndaymissed.setText("CHECK");
        btndaymissed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaymissedActionPerformed(evt);
            }
        });
        getContentPane().add(btndaymissed);
        btndaymissed.setBounds(160, 280, 90, 25);

        btndaysigned.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btndaysigned.setText("CHECK");
        btndaysigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaysignedActionPerformed(evt);
            }
        });
        getContentPane().add(btndaysigned);
        btndaysigned.setBounds(160, 340, 90, 20);

        btnportal.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnportal.setText("LINK TO PORTAL");
        btnportal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnportalActionPerformed(evt);
            }
        });
        getContentPane().add(btnportal);
        btnportal.setBounds(440, 360, 160, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
       tfcode.setText(null);
       JOptionPane.showMessageDialog(null, "YOU'VE BEEN ROLLCALLED!");
       
      
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndateActionPerformed
        
        Date dt=new Date();
        
         JOptionPane.showMessageDialog(null, "today's date: "+dt+" .");
         
         
        
    }//GEN-LAST:event_btndateActionPerformed

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
       
        Intro su= new Intro();
        su.setVisible(true);
        su.setSize(550,512);
        
    }//GEN-LAST:event_btnsignoutActionPerformed

    private void btndaymissedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaymissedActionPerformed
        
        String dm;
      
       
       
       try{
          int count=1;
           
           if( tfcode.equals(null))
           {
               
               int daym=0;
               int sum=daym+count;
               
               JOptionPane.showMessageDialog(null,"The days missed "+ sum," The days missed",JOptionPane.PLAIN_MESSAGE);
               count++;
           }
           
           
       }
       catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "no matched");
        }
       
        
        
    }//GEN-LAST:event_btndaymissedActionPerformed

    private void btndaysignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaysignedActionPerformed
        String ds;
        
        try{
          int count=1;
           
           if( tfcode.equals(tfcode))
           {
               
               int days=0;
               int sum=days+count;
               
               JOptionPane.showMessageDialog(null,"The days signed "+ sum," The days signed in",JOptionPane.PLAIN_MESSAGE);
               count++;
           }
           
           
       }
       catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "no matched");
        }
        
    }//GEN-LAST:event_btndaysignedActionPerformed

    private void btnportalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnportalActionPerformed
       
        JOptionPane.showMessageDialog(null, "Go to this website to check:https://http://portal.covenantuniversity.edu.ng/");
        
    }//GEN-LAST:event_btnportalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndate;
    private javax.swing.JButton btndaymissed;
    private javax.swing.JButton btndaysigned;
    private javax.swing.JButton btnportal;
    private javax.swing.JButton btnsignout;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfcode;
    // End of variables declaration//GEN-END:variables
}
