/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rollcall;

import javax.swing.JOptionPane;

/**
 *
 * @author EMEKA
 */
public class Signin extends javax.swing.JFrame {

    /**
     * Creates new form Signin
     */
    public Signin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfmatric = new javax.swing.JTextField();
        pfpassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        btnsignin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROLL CALL SERVICE LOGIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 490, 60);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 127, 150, 15);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("MATRICULATION NUMBER");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 38, 180, 15);

        tfmatric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmatricActionPerformed(evt);
            }
        });
        jPanel3.add(tfmatric);
        tfmatric.setBounds(218, 36, 200, 20);
        jPanel3.add(pfpassword);
        pfpassword.setBounds(218, 122, 200, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 60, 560, 210);

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setLayout(null);

        btnsignin.setBackground(new java.awt.Color(0, 0, 204));
        btnsignin.setFont(new java.awt.Font("Times New Roman", 2, 10)); // NOI18N
        btnsignin.setText("SIGN IN");
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        jPanel4.add(btnsignin);
        btnsignin.setBounds(243, 35, 67, 21);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        jLabel4.setText("POWERED  BY  EDS");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 62, 107, 28);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 270, 560, 90);

        jLabel5.setText("logo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 10, 20, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfmatricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmatricActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmatricActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        String matric=tfmatric.getText();
        String password=pfpassword.getText();
        
        
        if(tfmatric.equals(tfmatric.getText()))
        {
            //JOptionPane.showMessageDialog(null, " CORRECT MATRIC NUMBER");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "WRONG.INPUT CORRECT MATRIC NUMBER");
        }
        
        
        if(pfpassword.equals(pfpassword.getText()))
        {
            //JOptionPane.showMessageDialog(null, " CORRECT PASSWORD");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "WRONG.INPUT CORRECT PASSWORD");
        }
        
        
        try{
            JOptionPane.showMessageDialog(null, "Okay. Now Check your email and proceed");
            
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "sorry, no connection");
        }
        
      
        tfmatric.setText(null);
        pfpassword.setText(null);
       
        Homepage hp=new Homepage();
        hp.setVisible(true);
        hp.setSize(600,412);
        
        
    }//GEN-LAST:event_btnsigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfmatric;
    // End of variables declaration//GEN-END:variables
}
